name = "was-geht-stutensee"
main = "src/worker.js"
compatibility_date = "2025-04-01"
workers_dev = true

[[d1_databases]]
binding = "STUTENSEE_DB"
database_name = "was-geht-stutensee"
database_id = "ed273231-91e6-4c9b-bb72-02d0658baf62"
